In [ ]:
!pip install git+https://github.com/JustAnotherArchivist/snscrape.git -q

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for snscrape (pyproject.toml) ... done

In [ ]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

In [ ]:
query = 'ChatGPT until:2023-01-10 since:2023-01-01'
limit = 100000
tweets_1 = []
for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    #print(vars(tweet))
    #break
    if len(tweets_1) == limit:
        break
    else:
        tweets_1.append([tweet.id,
                       tweet.user.username,
                       tweet.user.verified,
                       tweet.user.location,
                       tweet.user.followersCount,
                       tweet.rawContent,
                       tweet.date,
                       tweet.retweetedTweet,
                       tweet.lang, tweet.retweetCount])
df_1 = pd.DataFrame(tweets_1, columns = ['UserId',
                                     'UserName',
                                     'Verified',
                                     'Location',
                                     'Followers',
                                     'Tweet',
                                     'Date',
                                     'Retweeted',
                                     'Language', 'retweetCount'])
df_1.head()
df_1.to_csv('/content/drive/MyDrive/Sentiment_Analysis/extracted_files/ChatGPT_Sentiment/jan_2023.csv', index=False)

In [ ]:
query = 'ChatGPT until:2023-01-31 since:2023-01-11'
limit = 100000
tweets_1 = []
for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    #print(vars(tweet))
    #break
    if len(tweets_1) == limit:
        break
    else:
        tweets_1.append([tweet.id,
                       tweet.user.username,
                       tweet.user.verified,
                       tweet.user.location,
                       tweet.user.followersCount,
                       tweet.rawContent,
                       tweet.date,
                       tweet.retweetedTweet,
                       tweet.lang, tweet.retweetCount])
df_1 = pd.DataFrame(tweets_1, columns = ['UserId',
                                     'UserName',
                                     'Verified',
                                     'Location',
                                     'Followers',
                                     'Tweet',
                                     'Date',
                                     'Retweeted',
                                     'Language', 'retweetCount'])
df_1.head()
df_1.to_csv('/content/drive/MyDrive/Sentiment_Analysis/extracted_files/ChatGPT_Sentiment/jan_2023_2.csv', index=False)

### Define a functin to loop through the folder and load the csv files containing certain defiend file name

In [ ]:
import os
import pandas as pd

def load_and_concat_data(folder_path, keyword, output_file):
    """
    Load and concatenate all datasets in a folder containing a specific keyword in the filename.

    Parameters:
    folder_path (str): Path to the folder containing the datasets.
    keyword (str): Keyword to search for in the filenames of the datasets to be loaded.
    output_file (str): Path to the output CSV file.

    Returns:
    None
    """
    # Find all files in the folder containing the keyword in the filename
    file_paths = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if keyword in f]

    # Load all files into a list of dataframes
    dfs = [pd.read_csv(file_path, low_memory=False) for file_path in file_paths]

    # Concatenate the dataframes into a single dataframe
    concatenated_df = pd.concat(dfs, ignore_index=True)

    # Save the concatenated dataframe to a CSV file
    concatenated_df.to_csv(output_file, index=False)

    print(f"Loaded and concatenated {len(dfs)} datasets. Saved to {output_file}")

In [ ]:
load_and_concat_data('/content/drive/MyDrive/Sentiment_Analysis/extracted_files/ChatGPT_Sentiment',
                     '2023',
                     '/content/drive/MyDrive/Sentiment_Analysis/extracted_files/ChatGPT_Sentiment/Chatgpt_sentiment.csv')

Loaded and concatenated 8 datasets. Saved to /content/drive/MyDrive/Sentiment_Analysis/extracted_files/ChatGPT_Sentiment/Chatgpt_sentiment.csv

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Sentiment_Analysis/extracted_files/ChatGPT_Sentiment/Chatgpt_sentiment.csv', low_memory=False)
data.head()

,Unnamed: 0,UserId,UserName,Verified,Location,Followers,Tweet,Date,Retweeted,Language,coordinates,retweetCount
0,0.0,1657898869802545152,adamludwick1,False,Fourth Rock from the Sun,50.0,@RobBobberschlob @jimmy_wales Better I suppose...,2023-05-15 00:01:07+00:00,NaN,en,NaN,NaN
1,1.0,1657898860986134528,lhsprix,False,NaN,330.0,OPEN FOR PREMIUM ACCOUNT!\n\nüåºDisney PH\nüåºNetf...,2023-05-15 00:01:05+00:00,NaN,en,NaN,NaN
2,2.0,1657898858473574410,fabiosports,False,Brasil,38.0,@severogauderio Serve essa ajuda do ChatGPT? h...,2023-05-15 00:01:04+00:00,NaN,pt,NaN,NaN
3,3.0,1657898853381857281,goodyear1212121,False,NaN,1880.0,https://t.co/TPBjwjem6z\n‰Ωø„Å£„Å¶„Åø„Åü\n\n„Åæ„Å†Ë©¶È®ìÈÅãÁî®‰∏≠„Å†„Åë„Å©„ÇØ„ÇΩ...,2023-05-15 00:01:03+00:00,NaN,ja,NaN,NaN
4,4.0,1657898850630381568,Lumin_VR,False,‚ñº„Éï„É¨„É≥„ÉâÁôªÈå≤„ÅØ„Åì„Å°„Çâ‚ñº ‚ñ∂‚ñ∂,477.0,chatgpt„ÅÆ„Éó„É©„Ç∞„Ç§„É≥ËøΩ„ÅÑÂàá„Çå„Å¶„Å™„ÅÑ„Åë„Å©„ÇÑ„Åπ„Éº„Å™,2023-05-15 00:01:02+00:00,NaN,ja,NaN,NaN

In [ ]:
data = data.drop(['Unnamed: 0', 'Retweeted','coordinates','retweetCount'], axis=1)
data.head()

,UserId,UserName,Verified,Location,Followers,Tweet,Date,Language
0,1657898869802545152,adamludwick1,False,Fourth Rock from the Sun,50.0,@RobBobberschlob @jimmy_wales Better I suppose...,2023-05-15 00:01:07+00:00,en
1,1657898860986134528,lhsprix,False,NaN,330.0,OPEN FOR PREMIUM ACCOUNT!\n\nüåºDisney PH\nüåºNetf...,2023-05-15 00:01:05+00:00,en
2,1657898858473574410,fabiosports,False,Brasil,38.0,@severogauderio Serve essa ajuda do ChatGPT? h...,2023-05-15 00:01:04+00:00,pt
3,1657898853381857281,goodyear1212121,False,NaN,1880.0,https://t.co/TPBjwjem6z\n‰Ωø„Å£„Å¶„Åø„Åü\n\n„Åæ„Å†Ë©¶È®ìÈÅãÁî®‰∏≠„Å†„Åë„Å©„ÇØ„ÇΩ...,2023-05-15 00:01:03+00:00,ja
4,1657898850630381568,Lumin_VR,False,‚ñº„Éï„É¨„É≥„ÉâÁôªÈå≤„ÅØ„Åì„Å°„Çâ‚ñº ‚ñ∂‚ñ∂,477.0,chatgpt„ÅÆ„Éó„É©„Ç∞„Ç§„É≥ËøΩ„ÅÑÂàá„Çå„Å¶„Å™„ÅÑ„Åë„Å©„ÇÑ„Åπ„Éº„Å™,2023-05-15 00:01:02+00:00,ja

In [ ]:
len(data.columns)

8